version: '3.8'
services:
  chatbot:
    build: .
    container_name: golang-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=${PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - BUCKET_BASE_URL=${BUCKET_BASE_URL}
      - PROMPT_FILE_PATTERN=${PROMPT_FILE_PATTERN}
      - BUCKET_SIGNER_URL=${BUCKET_SIGNER_URL}
      - BUCKET_NAME=${BUCKET_NAME}
    command: ["go", "run", "main.go"]
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - chatnet

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - N8N_BASIC_AUTH_ACTIVE=false
      - DB_TYPE=sqlite
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=http://localhost:5678
      - IG_PAGE_TOKEN=EAAJDBs8LY5MBOwOtZBFImezFUYMOAngZAoRxmTZA7L68bnXAGbLmoZAbcf7Xk3HO7PPZAolL9tZC7ZAQ62tArSmTZCwJjc2pvkBflbSblk0xiVRN4Lwh46XLBqZCYZBBvOrziIXVEcD9xXqFsnXQYEe5HJhqWNL1932GRRrBgb2tWGjP9XGqMZBf1nlcrmpWd99FWLZBt8vUbKE6uWHPBsavCeff0xGIyoSfmzGbyb4schyoZAfIZD
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - chatnet

volumes:
  pg_data:
  n8n_data:

networks:
  chatnet:
    driver: bridge