basePath: /
definitions:
  controller.ChatRequest:
    properties:
      cliente_id:
        type: string
      message:
        type: string
    type: object
  controller.ChatResponse:
    properties:
      response:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: suporte@chatbotwhitelabel.com
    name: Equipe Técnica
  description: API para atendimento inteligente com IA e configuração via bucket
  title: Chatbot
  version: "2.0"
paths:
  /atendimento:
    post:
      consumes:
      - application/json
      description: Recebe uma mensagem do usuário e responde com base na IA e no prompt
        dinâmico do cliente
      parameters:
      - description: Mensagem do usuário com cliente_id
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/controller.ChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ChatResponse'
        "400":
          description: Requisição inválida
          schema:
            type: string
        "500":
          description: Erro interno do servidor
          schema:
            type: string
      summary: Atendimento inteligente com IA
      tags:
      - atendimento
swagger: "2.0"
